# Generated by Django 4.2.6 on 2024-07-09 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tema', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('opcionA', models.CharField(max_length=200, null=True)),
                ('opcionB', models.CharField(max_length=200, null=True)),
                ('opcionC', models.CharField(max_length=200, null=True)),
                ('opcionD', models.CharField(max_length=200, null=True)),
                ('correcta', models.CharField(choices=[('A', 'A'), ('C', 'C'), ('B', 'B'), ('D', 'D')], max_length=10, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='pivote.test')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(auto_now=True, null=True)),
                ('contenido', models.CharField(blank=True, max_length=1000, null=True)),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pivote.asignatura')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
