# Generated by Django 4.2.5 on 2024-05-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
