# Generated by Django 4.2.6 on 2024-07-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivote', '0002_test_pregunta_alternativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('SM', 'Seleccion Multiple'), ('D', 'Desarrollo')], max_length=10, null=True),
        ),
    ]
