# Generated by Django 4.2.6 on 2024-07-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivote', '0003_alter_pregunta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='respuestaCorrectaTexto',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='respuestaTexto',
            field=models.TextField(default='none'),
        ),
    ]
