# Generated by Django 4.2.6 on 2024-07-04 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivote', '0004_pregunta_respuestacorrectatexto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pivote.pregunta'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuestaCorrectaTexto',
            field=models.TextField(blank=True, default='Respuesta', null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuestaTexto',
            field=models.TextField(blank=True, default='Respuesta', null=True),
        ),
    ]
