# Generated by Django 4.2.6 on 2024-07-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivote', '0005_alter_alternativa_pregunta_alter_alternativa_texto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='respuestaCorrectaTexto',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuestaTexto',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='respuestaCorrecta',
            field=models.BooleanField(),
        ),
    ]
