# Generated by Django 4.2.6 on 2024-07-05 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivote', '0006_remove_pregunta_respuestacorrectatexto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='pivote.pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='pivote.test'),
        ),
    ]
