# Generated by Django 4.2.6 on 2024-07-05 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivote', '0007_alter_alternativa_pregunta_alter_pregunta_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='pivote.pregunta'),
        ),
    ]
