# Generated by Django 4.2.6 on 2024-07-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivote', '0009_alter_alternativa_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='correcta',
            field=models.CharField(choices=[('a', 'A'), ('c', 'C'), ('b', 'B'), ('d', 'D')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='opcionA',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='opcionB',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='opcionC',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='opcionD',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Alternativa',
        ),
    ]
