# Generated by Django 4.2.6 on 2024-07-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivote', '0010_pregunta_correcta_pregunta_opciona_pregunta_opcionb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='correcta',
            field=models.CharField(choices=[('3', 'C'), ('2', 'B'), ('1', 'A'), ('4', 'D')], max_length=10, null=True),
        ),
    ]
