# Generated by Django 4.2.6 on 2024-07-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivote', '0011_alter_pregunta_correcta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='correcta',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='a_correcta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='b_correcta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='c_correcta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='d_correcta',
            field=models.BooleanField(default=False),
        ),
    ]
