# Generated by Django 4.2.6 on 2024-07-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivote', '0012_remove_pregunta_correcta_pregunta_a_correcta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='a_correcta',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='b_correcta',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='c_correcta',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='d_correcta',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='correcta',
            field=models.CharField(choices=[('1', 'A'), ('3', 'C'), ('2', 'B'), ('D', 'D')], max_length=10, null=True),
        ),
    ]
