# Generated by Django 4.2.6 on 2024-07-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivote', '0013_remove_pregunta_a_correcta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='correcta',
            field=models.CharField(choices=[('A', 'A'), ('C', 'C'), ('D', 'D'), ('B', 'B')], max_length=10, null=True),
        ),
    ]
